# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://"mark-watson".github.io/"question_answering"/"

git_url = "https://github.com/"mark-watson"/"question_answering"/tree/{branch}/"

def custom_doc_links(name): return None
