# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"qa": "00_core.ipynb",
         "nlp_model": "00_core.ipynb",
         "query": "00_core.ipynb",
         "entities_in_text": "00_core.ipynb",
         "dbpedia_get_entities_by_name": "00_core.ipynb",
         "QA": "00_core.ipynb",
         "sparql": "00_core.ipynb",
         "entity_type_to_type_uri": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://{user}.github.io/{lib_name}/"

git_url = "https://github.com/{user}/{lib_name}/tree/{branch}/"

def custom_doc_links(name): return None
