# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"qa": "00_core.ipynb",
         "nlp_model": "00_core.ipynb",
         "query": "00_core.ipynb",
         "entities_in_text": "00_core.ipynb",
         "dbpedia_get_entities_by_name": "00_core.ipynb",
         "QA": "00_core.ipynb",
         "sparql": "00_core.ipynb",
         "entity_type_to_type_uri": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://mark-watson.github.io/question_answering/"

git_url = "https://github.com/mark-watson/question_answering/tree/main/"

def custom_doc_links(name): return None
